Repository SocialSisterYi/bilibili-API-collect, pull requests merged in 2022-11, with the labels that each got.

#534 修正分区视频排行榜
  ranking&dynamic/ranking.md
Labels: 错误/MISTAKES, 视频/Video

#537 添加老粉计划
  user/contract.md
  user/info.md
Labels: 用户/Member

#538 评论接口失效
  comment/list.md
Labels: 错误/MISTAKES, 评论/Reply
