Repository SocialSisterYi/bilibili-API-collect, pull requests merged in 2022-12, with the labels that each got.

#547 查询用户投稿视频明细 -1200：被降级过滤的请求
  user/space.md
Labels: 新增/ADD, 主站杂项/Misc

#544 增加 最近更新UP主列表
  dynamic/get_dynamic_detail.md
Labels: 新增/ADD, 动态/Dynamic

#542 Update skin.md
  garb/skin.md
Labels: 新增/ADD, 客户端/App

#541 Update 大积分改变记录
  vip/center.md
Labels: 新增/ADD, 大会员/Vip

#540 增加 Manga Activity/ShareComic
  manga/Activity.md
Labels: 新增/ADD, 漫画/Manga

#539 Create Season.md 漫画赛季
  README.md
  manga/Season.md
Labels: 新增/ADD, 漫画/Manga

#554 B币方式充电响应字段 bp_num 变更为字符串类型(#251)
  electric/Bcoin.md
Labels: 错误/MISTAKES, 支付/Pay

#553 更正 tv 登录响应数据 (#113)
  login/login_action/QR.md
Labels: 错误/MISTAKES, 账号相关/Account

#552 更新 clockin.md Cookie 鉴权的条件
  vip/clockin.md
Labels: 错误/MISTAKES, 大会员/Vip

#550 Fixed 'im.proto' package name.
  grpc_api/bilibili/im/interfaces/v1/im.proto
Labels: 错误/MISTAKES, 客户端/App, gRpcAPI

#557 更新 `契约` 相关 proto 目录结构
  grpc_api/bilibili/polymer/contract/v1/contract.proto
Labels: 错误/MISTAKES, gRpcAPI

#565 增加视频评论 `grpc` 接口中图片相关字段
  grpc_api/bilibili/main/community/reply/v1/reply.proto
Labels: 评论/Reply, gRpcAPI

#564 Update space.md
  user/space.md
Labels: 错误/MISTAKES, 用户/Member

#563 Update judgement_info.md ：修正部分错误的链接
  blackroom/jury/judgement_info.md
Labels: 错误/MISTAKES, 主站杂项/Misc
