Repository SocialSisterYi/bilibili-API-collect, pull requests merged in 2023-08, with the labels that each got.

#771 补充用户名片信息遗漏的签名
  docs/user/info.md
Labels: 新增/ADD, 错误/MISTAKES, 用户/Member

#774 fix: unite grpc api protos from 7.41.0+
  grpc_api/bilibili/app/playerunite/v1/playerunite.proto
  grpc_api/bilibili/app/viewunite/common.proto
  grpc_api/bilibili/app/viewunite/pgcanymodel.proto
  grpc_api/bilibili/app/viewunite/ugcanymodel.proto
  grpc_api/bilibili/app/viewunite/v1/viewunite.proto
  grpc_api/bilibili/playershared/playershared.proto
Labels: 新增/ADD, gRpcAPI

#769 删改io/ioutil和time.Now().Sub
  docs/misc/sign/wbi.md
Labels: 错误/MISTAKES, 主站杂项/Misc

#785 Update statistics&data.md
  docs/creativecenter/statistics&data.md
Labels: 错误/MISTAKES, 视频/Video, 主站杂项/Misc

#784 添加 Github Action 运行仓库判断 close #783
  .github/workflows/vuepress-deploy.yml
Labels: 错误/MISTAKES, 想法/IDEA

#777 优化示例代码
  docs/misc/sign/wbi.md
Labels: 想法/IDEA

#782 [API修改] 风纪委员会获取案件信息
  docs/blackroom/jury/judgement_info.md
Labels: 错误/MISTAKES, 主站杂项/Misc

#786 添加了生成CorrespondPath算法的kotlin实现
  docs/login/cookie_refresh.md
Labels: 新增/ADD

#787 feat: `features: itemOpusStyle`
  docs/dynamic/space.md
Labels: 动态/Dynamic

#792 增加 /x/v2/dm/web/seg.so 弹幕接口的认证说明
  docs/danmaku/danmaku_proto.md
Labels: 新增/ADD, 弹幕/Danmaku
