Repository SocialSisterYi/bilibili-API-collect, pull requests merged in 2023-10, with the labels that each got.

#827 标注部分 wbi 链接
  docs/article/list.md
  docs/comment/list.md
  docs/danmaku/danmaku_proto.md
  docs/search/hot.md
  docs/search/search_request.md
  docs/user/space.md
  docs/video/info.md
  docs/video/videostream_url.md
Labels: 专栏/Article, 主站杂项/Misc

#829 Update pagesize to page_size
  docs/search/search_request.md
Labels: 错误/Mistakes

#834 fix bvid_desc.md av2bv
  docs/misc/bvid_desc.md
Labels: 错误/Mistakes

#833 update grpc proto from 7.49.0
  grpc_api/bilibili/api/probe/v1/probe.proto
  grpc_api/bilibili/api/ticket/v1/ticket.proto
  grpc_api/bilibili/app/click/v1/heartbeat.proto
  grpc_api/bilibili/app/dynamic/v2/opus.proto
  grpc_api/bilibili/app/interfaces/v1/history.proto
  grpc_api/bilibili/app/interfaces/v1/media.proto
  grpc_api/bilibili/app/listener/v1/listener.proto
  grpc_api/bilibili/app/mine/v1/mine.proto
  grpc_api/bilibili/app/nativeact/v1/nativeact.proto
  grpc_api/bilibili/app/playerunite/ugcanymodel/ugcanymodel.proto
  grpc_api/bilibili/app/playurl/v1/playurl.proto
  grpc_api/bilibili/app/search/v2/search.proto
  grpc_api/bilibili/dynamic/common/dynamic.proto
  grpc_api/bilibili/dynamic/gw/gateway.proto
  grpc_api/bilibili/dynamic/interfaces/campus/v1/api.proto
  grpc_api/bilibili/dynamic/interfaces/feed/v1/api.proto
  grpc_api/bilibili/gaia/gw/gw_api.proto
Labels: 新增/Add, GRpcAPI

#836 fix: grpc proto name collision
  grpc_api/bilibili/dynamic/common/dynamic.proto
Labels: 错误/Mistakes, GRpcAPI

#838 修复某些表格全角&半角符号不分
  docs/live/manage.md
  docs/video_ranking/precious_videos.md
Labels: 错误/Mistakes, 文档/Document

#844 Update action.md
  docs/comment/action.md
Labels: 新增/Add, 主站杂项/Misc

#842 添加 GitHub trending badge 到 README.md
  README.md
Labels: 新增/Add, 文档/Document
