Repository SocialSisterYi/bilibili-API-collect, pull requests merged in 2023-11, with the labels that each got.

#849 center github trending badge
  README.md
Labels: 文档/Document, 更新/Update

#851 update user doc list
  docs/user/space.md
Labels: 用户/Member, 更新/Update

#853 fix: remove invalid client_info api
  docs/clientinfo/client_info.md
Labels: 错误/Mistakes, 主站杂项/Misc

#855 补充视频分区及移除无效链接
  README.md
  docs/video/video_zone.md
Labels: 视频/Video

#857 更新 bvid 算法
  docs/misc/bvid_desc.md
Labels: 视频/Video, 更新/Update

#860 添加了生成CorrespondPath算法的Go实现
  docs/login/cookie_refresh.md
Labels: 新增/Add, 文档/Document

#862 更新 bvid 算法
  docs/misc/bvid_desc.md
Labels: 新增/Add, 文档/Document

#865 增加AI摘要文档
  assets/img/aiSummary.svg
  docs/video/summary.md
Labels: 新增/Add, 视频/Video

#873 更新x/vip/privilege/my
  docs/vip/info.md
Labels: 大会员/Vip, 更新/Update

#874 Update search.proto
  grpc_api/bilibili/app/search/v2/search.proto
Labels: 错误/Mistakes, 文档/Document

#875 修改 /vip/privilege/my 错误
  docs/vip/info.md
Labels: 错误/Mistakes, 大会员/Vip

#877 Update action.md 大会员每日经验
  docs/vip/action.md
Labels: 新增/Add, 大会员/Vip

#879 fix: typo
  README.md
Labels: 错误/Mistakes, 文档/Document

#880 update dynamic/all.md
  docs/dynamic/all.md
Labels: 动态/Dynamic, 更新/Update
