Repository SocialSisterYi/bilibili-API-collect, pull requests merged in 2023-05, with the labels that each got.

#666 补充 Official 对象中的认证类型信息
  README.md
  docs/dynamic/get_dynamic_detail.md
  docs/login/login_info.md
  docs/user/info.md
  docs/user/official_role.md
  docs/video/info.md
Labels: 新增/ADD, 用户/Member

#660 添加评论条目中图片数据说明
  docs/comment/readme.md
Labels: 新增/ADD, 评论/Reply

#673 更新获取视频超详细信息中的部分描述
  docs/video/info.md
Labels: 新增/ADD, 视频/Video

#681 [gRpc] 添加评论区 At 用户列表接口
  grpc_api/bilibili/relation/interfaces/api.proto
  grpc_api/readme.md
Labels: 新增/ADD, 用户/Member, 客户端/App, gRpcAPI

#687 Update member_center.md
  docs/login/member_center.md
Labels: 新增/ADD, 账号相关/Account

#684 修正wbi文档中的一些描述错误
  docs/misc/sign/wbi.md
Labels: 错误/MISTAKES

#688 Update login_info.md
  docs/login/login_info.md
Labels: 新增/ADD, 账号相关/Account

#685 添加app短信登录接口
  docs/login/login_action/SMS.md
Labels: 新增/ADD, 账号相关/Account

#690 增加评论接口响应码
  docs/comment/action.md
Labels: 新增/ADD, 评论/Reply
