Repository SocialSisterYi/bilibili-API-collect, pull requests merged in 2023-07, with the labels that each got.

#729 feature: App Sign 添加java版本实现
  docs/misc/sign/APP.md
Labels: 新增/ADD

#731 Fix language list error
  docs/misc/sign/wbi.md
Labels: 错误/MISTAKES

#728 update grpc_api from 7.26.0
  grpc_api/bilibili/app/dynamic/common/dynamic.proto
  grpc_api/bilibili/app/dynamic/v2/campus.proto
  grpc_api/bilibili/app/dynamic/v2/dynamic.proto
  grpc_api/bilibili/app/dynamic/v2/opus.proto
  grpc_api/bilibili/app/search/v2/search.proto
  grpc_api/bilibili/app/viewunite/v1/viewunite.proto
  grpc_api/bilibili/broadcast/message/main/search.proto
  grpc_api/bilibili/pgc/gateway/player/v2/playurl.proto
  grpc_api/bilibili/pgc/gateway/player/v3/playurl.proto
  grpc_api/bilibili/playershared/playershared.proto
  grpc_api/bilibili/polymer/app/search/v1/search.proto
  grpc_api/bilibili/polymer/contract/v1/contract.proto
Labels: gRpcAPI

#741 add grpc docs
  docs/misc/device_identity.md
  grpc_api/bilibili/metadata/fawkes/fawkes.proto
  grpc_api/bilibili/metadata/metadata.proto
  grpc_api/bilibili/metadata/parabox/parabox.proto
  grpc_api/readme.md
Labels: 客户端/App, gRpcAPI

#743 修复gRPC协议文件的一些错误
  grpc_api/bilibili/app/distribution/v1/distribution.proto
  grpc_api/bilibili/app/dynamic/v2/campus.proto
  grpc_api/bilibili/app/dynamic/v2/dynamic.proto
  grpc_api/bilibili/app/interfaces/v1/history.proto
  grpc_api/bilibili/app/interfaces/v1/media.proto
  grpc_api/bilibili/app/interfaces/v1/search.proto
  grpc_api/bilibili/app/interfaces/v1/space.proto
  grpc_api/bilibili/app/listener/v1/listener.proto
  grpc_api/bilibili/dagw/component/avatar/v1/avatar.proto
  grpc_api/bilibili/dagw/component/avatar/v1/plugin.proto
Labels: 错误/MISTAKES, gRpcAPI

#748 feat: 更新直播流数据包内容，修复typo
  docs/live/message_stream.md
Labels: 新增/ADD, 直播/Live

#752 :sparkles: feat(直播间管理 API): 添加更新公告与标签 API
  docs/live/manage.md
Labels: 新增/ADD, 直播/Live

#754 update grpc message from 7.29.0
  grpc_api/bilibili/api/ticket/v1/ticket.proto
  grpc_api/bilibili/metadata/fawkes/fawkes.proto
  grpc_api/datacenter/hakase/protobuf/android_device_info.proto
Labels: 新增/ADD, 客户端/App, gRpcAPI

#762 修复错误的数据类型
  grpc_api/bilibili/api/ticket/v1/ticket.proto
Labels: 错误/MISTAKES

#761 文档好像写错了
  docs/misc/sign/APPKey.md
Labels: 错误/MISTAKES

#763 补充手机端热搜列表参数与属性
  docs/search/hot.md
Labels: 新增/ADD, 主站杂项/Misc, 客户端/App
