Repository SocialSisterYi/bilibili-API-collect, pull requests merged in 2023-02, with the labels that each got.

#615 Update statistics&data.md
  creativecenter/statistics&data.md
Labels: 错误/MISTAKES, 用户/Member

#612 danmaku/danmaku_proto: typo fix
  danmaku/danmaku_proto.md
Labels: 错误/MISTAKES, 弹幕/Danmaku

#607 添加 label_style 字段
  video/info.md
Labels: 大会员/Vip

#608 更新 user/search 接口
  user/space.md
Labels: 新增/ADD, 用户/Member

#611 添加轻享卡相关接口
  manga/light_card.md
Labels: 新增/ADD, 漫画/Manga

#619 添加直播签到信息获取
  live/user.md
Labels: 新增/ADD, 直播/Live

#617 添加漫画补签
  manga/ClockIn.md
Labels: 新增/ADD, 漫画/Manga

#616 什么光速合并，我甚至还没改完
  creativecenter/statistics&data.md
Labels: 新增/ADD, 用户/Member

#626 新增包月充电功能相关API
  README.md
  docs/electric/charge_list.md
  docs/electric/charge_msg.md
  docs/electric/monthly.md
  docs/user/relation.md
Labels: 新增/ADD, 支付/Pay

#625 添加新的grpc_api proto(from 7.18.0)
  grpc_api/bilibili/community/interfacess/biligram/v1/biligram.proto
  grpc_api/bilibili/dagw/component/avatar/common/common.proto
  grpc_api/bilibili/dagw/component/avatar/v1/avatar.proto
  grpc_api/bilibili/dynamic/interfaces/campus/v1/api.proto
  grpc_api/bilibili/pangu/gallery/v1/openplatform/apiserver/v1alpha1/api.proto
  grpc_api/bilibili/pgc/gateway/player/v3/playurl.proto
  grpc_api/bilibili/playershared/playershared.proto
  grpc_api/bilibili/polymer/contract/contract.proto
  grpc_api/bilibili/relation/interfaces/api.proto
  grpc_api/bilibili/render/render.proto
  grpc_api/pgc/gateway/vega/v1/vega.proto
Labels: 新增/ADD, 错误/MISTAKES, gRpcAPI

#629 修正轻享卡信息
  docs/manga/light_card.md
Labels: 新增/ADD, 漫画/Manga

#624 增添部分注释
  grpc_api/bilibili/app/archive/middleware/v1/preload.proto
  grpc_api/bilibili/metadata/device/device.proto
  grpc_api/bilibili/metadata/metadata.proto
  grpc_api/bilibili/metadata/restriction/restriction.proto
  grpc_api/bilibili/pagination/pagination.proto
  grpc_api/bilibili/pgc/gateway/player/v2/playurl.proto
  grpc_api/bilibili/polymer/app/search/v1/search.proto
Labels: 新增/ADD, gRpcAPI
