Repository SocialSisterYi/bilibili-API-collect, pull requests merged in 2023-09, with the labels that each got.

#805 删除了前段时间新增但已取消的字段
  docs/live/message_stream.md
Labels: 直播/Live

#806 fix: 修正文档中存在的错误路径，标签和目录
  docs/dynamic/card_info.md
  docs/history&toview/history.md
  docs/history&toview/toview.md
  docs/live/manage.md
  docs/login/login_action/password.md
  docs/manga/Download.md
  docs/user/space.md
  docs/video/videostream_url.md
  docs/video_ranking/dynamic.md
  docs/video_ranking/popular.md
  docs/video_ranking/ranking.md
Labels: 文档/Document, 更新/Update

#807 chore: 升级为 vuepress@2
  .vuepress/client.js
  .vuepress/config.js
  .vuepress/theme/index.js
  .vuepress/theme/layouts/Layout.vue
  CONTRIBUTING.md
  README.md
  docs/danmaku/danmaku_xml.md
  package.json
  yarn.lock
Labels: 文档/Document, 更新/Update

#816 为文档增加了search插件
  .vuepress/config.js
  package.json
  yarn.lock
Labels: 新增/Add, 文档/Document

#817 fix: 移除失效nav接口, 添加未登录状态nav请求响应实例
  docs/login/login_info.md
Labels: 新增/Add, 账号相关/Account, 更新/Update

#820 Update railgun.md
  docs/creativecenter/railgun.md
Labels: 用户/Member, 主站杂项/Misc, 更新/Update

#824 Update bvid_desc.md
  docs/misc/bvid_desc.md
Labels: 主站杂项/Misc, 更新/Update

#825 Update `new_face_version`
  docs/message/private_msg.md
Labels: 新增/Add, 主站杂项/Misc
