Repository SocialSisterYi/bilibili-API-collect, pull requests merged in 2024-02, with the labels that each got.

#959 Add short video recommend api
  docs/video/recommend.md
Labels: 新增/Add, 视频/Video, 客户端/App

#963 修复BV号av号转换算法的 python 实现中的类型错误，提高可读性
  docs/misc/bvid_desc.md
Labels: 错误/Mistakes, 文档/Document

#972 完善 message_stream.md
  docs/live/message_stream.md
Labels: 错误/Mistakes, 主站杂项/Misc

#973 Update ranking.md
  docs/video_ranking/ranking.md
Labels: 新增/Add, 文档/Document
