Repository SocialSisterYi/bilibili-API-collect, pull requests merged in 2024-04, with the labels that each got.

#991 修复demo访问/x/web-interface/nav出现被ban的情况
  docs/misc/sign/wbi.md
Labels: 错误/Mistakes, 主站杂项/Misc, 文档/Document

#995 Update ranking.md
  docs/video_ranking/ranking.md
Labels: 错误/Mistakes, 主站杂项/Misc

#997 Fix #994
  docs/electric/charge_list.md
  docs/misc/errcode.md
Labels: 错误/Mistakes, 主站杂项/Misc

#1000 fix: typo
  docs/login/member_center.md
Labels: 错误/Mistakes, 文档/Document

#1002 修正了用户名片信息的响应示例数据结构
  docs/user/info.md
Labels: 错误/Mistakes

#1003 fix: typo
  docs/fav/info.md
Labels: 错误/Mistakes, 文档/Document

#1005 issue 表单语法错误 1-update-request.yml
  .github/ISSUE_TEMPLATE /1-update-request.yml
Labels: 错误/Mistakes, 文档/Document

#1004 Add user-agent http header when curl download video
  docs/video/videostream_url.md
Labels: 错误/Mistakes, 视频/Video
