Repository SocialSisterYi/bilibili-API-collect, pull requests merged in 2024-05, with the labels that each got.

#1012 修正部分错误
  docs/video/collection.md
Labels: 错误/Mistakes, 主站杂项/Misc

#659 智能防挡弹幕
  docs/danmaku/webmask.md
  docs/video/player.md
Labels: 新增/Add, 弹幕/Danmaku

#1017 feat: cookie刷新生成CorrespondPath算法添加java代码实现
  docs/login/cookie_refresh.md
Labels: 新增/Add, 文档/Document

#1021 feat: bv<-->av 增加java实现
  docs/misc/bvid_desc.md
Labels: 新增/Add, 文档/Document
