Repository SocialSisterYi/bilibili-API-collect, pull requests merged in 2024-06, with the labels that each got.

#1035 wbi、av2bv、bv2av 的 c++ 实现
  docs/misc/bvid_desc.md
  docs/misc/sign/APP.md
  docs/misc/sign/wbi.md
Labels: 新增/Add

#1034 Update wbi.md
  docs/misc/sign/wbi.md
Labels: 错误/Mistakes, 算法/Algorithm

#1031 feat. wbi签名算法添加typescript实现
  docs/misc/sign/wbi.md
Labels: 新增/Add, 算法/Algorithm

#1040 补充合集（收藏夹）state含义
  docs/user/space.md
Labels: 视频/Video, 更新/Update

#1027 feat: bv<-->av 算法在Golang的实现示例
  docs/misc/bvid_desc.md
Labels: 新增/Add, 算法/Algorithm

#1044 feat: 添加获取多用户信息接口，完善用户关系文档
  docs/user/info.md
  docs/user/relation.md
Labels: 新增/Add, 用户/Member

#1042 添加开播状态码60013
  docs/live/manage.md
Labels: 新增/Add, 直播/Live

#1041 [showcase] 提供一个基于 bilibili API collection 的成品项目
  README.md
Labels: 新增/Add, 文档/Document
