Repository SocialSisterYi/bilibili-API-collect, pull requests merged in 2024-08, with the labels that each got.

#1077 增加获取直播间主播信息
  README.md
  docs/live/info.md
Labels: 新增/Add, 错误/Mistakes, 文档/Document

#1081 剔除部分已经复活的账号
  docs/user/info.md
Labels: 文档/Document, 更新/Update

#1066 feat: 各种接口补充与错误修正
  .vuepress/theme/layouts/Layout.vue
  README.md
  docs/APP_widget/ver.md
  docs/activity/info.md
  docs/activity/list.md
  docs/clientinfo/ip.md
  docs/comment/list.md
  docs/creativecenter/season.md
  docs/creativecenter/upload.md
  docs/creativecenter/videos.md
  docs/customerservice/msg.md
  docs/danmaku/action.md
  docs/dynamic/all.md
  docs/dynamic/dynamic_enum.md
  docs/dynamic/topic.md
  docs/fav/info.md
  docs/garb/lottery.md
  docs/live/info.md
  docs/live/report.md
  docs/login/login_action/password.md
  docs/login/login_action/readme.md
  docs/login/login_notice.md
  docs/login/member_center.md
  docs/message/private_msg.md
  docs/misc/b23tv.md
  docs/misc/buvid3_4.md
  docs/misc/picture.md
  docs/misc/sign/bili_ticket.md
  docs/misc/sign/v_voucher.md
  docs/misc/sign/wbi.md
  docs/misc/time_stamp.md
  docs/search/hot.md
  docs/search/search_request.md
  docs/search/suggest.md
  docs/user/medals.md
  docs/user/space.md
  docs/user/status_number.md
  docs/video/collection.md
  docs/video/player.md
  docs/video/report.md
  docs/video/status_number.md
  docs/video/videostream_url.md
  docs/video_ranking/popular.md
  docs/video_ranking/precious_videos.md
  docs/wallet/info.md
  docs/web_widget/header.md
Labels: 新增/Add, 错误/Mistakes, 视频/Video, 账号相关/Account, 直播/Live, 动态/Dynamic, 弹幕/Danmaku, 评论/Reply, 投稿/Upload, 用户/Member, 主站杂项/Misc, 客户端/App, 文档/Document, 消息/Message
