Repository SocialSisterYi/bilibili-API-collect, pull requests merged in 2025-03, with the labels that each got.

#1185 下线两个接口（“检查昵称是否可注册”和“直播间用户实用 API”的直播签到）
  docs/live/user.md
  docs/user/check_nickname.md
Labels: 更新/Update

#1204 增加 获取合集中的视频 的api
  docs/creativecenter/season.md
Labels: 视频/Video

#1209 更新直播信息流文档
  docs/live/message_stream.md
Labels: 直播/Live
