Repository SocialSisterYi/bilibili-API-collect, pull requests merged in 2025-04, with the labels that each got.

#1140 禁言新增参数hour
  docs/live/silent_user_manage.md
Labels: 直播/Live

#1112 fix: 修复装扮/收藏集搜索API参数名称错误
  docs/garb/lottery.md
Labels: 主站杂项/Misc

#1208 优化wbi.md里的Swift代码
  docs/misc/sign/wbi.md
Labels: 算法/Algorithm

#1162 更新"查询每日投币获得经验数"
  docs/login/member_center.md
Labels: 账号相关/Account, 更新/Update

#1207 更新video的wbi/index/top/feed/rcmd api对商业推广视频的属性说明
  docs/video/recommend.md
Labels: 视频/Video, 更新/Update

#1186 Update space.md
  docs/dynamic/space.md
Labels: 用户/Member, 更新/Update

#1223 重构 wbi golang 实现
  docs/misc/sign/wbi.md
Labels: 算法/Algorithm

#1142 docs(message): 更新查询私信消息记录文档
  docs/message/private_msg.md
Labels: 消息/Message

#1158 Update player.md
  docs/video/player.md
Labels: 视频/Video

#1111 更新vip_pay_type状态说明
  docs/user/info.md
Labels: 大会员/Vip

#1149 更新分区信息
  docs/video/video_zone.md
Labels: 视频/Video

#1231 feat: 修改部分接口文档的描述，新增视频新版分区信息
  .vuepress/theme/layouts/Layout.vue
  README.md
  assets/zone_v2_icon/ai.svg
  assets/zone_v2_icon/animal.svg
  assets/zone_v2_icon/car.svg
  assets/zone_v2_icon/cinephile.svg
  assets/zone_v2_icon/dance.svg
  assets/zone_v2_icon/douga.svg
  assets/zone_v2_icon/emotion.svg
  assets/zone_v2_icon/entertainment.svg
  assets/zone_v2_icon/fashion.svg
  assets/zone_v2_icon/food.svg
  assets/zone_v2_icon/game.svg
  assets/zone_v2_icon/gym.svg
  assets/zone_v2_icon/handmake.svg
  assets/zone_v2_icon/health.svg
  assets/zone_v2_icon/home.svg
  assets/zone_v2_icon/information.svg
  assets/zone_v2_icon/kichiku.svg
  assets/zone_v2_icon/knowledge.svg
  assets/zone_v2_icon/life_experience.svg
  assets/zone_v2_icon/life_joy.svg
  assets/zone_v2_icon/music.svg
  assets/zone_v2_icon/outdoors.svg
  assets/zone_v2_icon/painting.svg
  assets/zone_v2_icon/parenting.svg
  assets/zone_v2_icon/rural.svg
  assets/zone_v2_icon/shortplay.svg
  assets/zone_v2_icon/sports.svg
  assets/zone_v2_icon/tech.svg
  assets/zone_v2_icon/travel.svg
  assets/zone_v2_icon/vlog.svg
  docs/article/action.md
  docs/article/delete.md
  docs/article/list.md
  docs/dynamic/action.md
  docs/dynamic/publish.md
  docs/electric/Bcoin.md
  docs/electric/WeChat&Alipay.md
  docs/electric/charge_list.md
  docs/electric/charge_msg.md
  docs/electric/monthly.md
  docs/message/private_msg.md
  docs/user/info.md
  docs/user/relation.md
  docs/user/space.md
  docs/video/info.md
  docs/video/video_zone.md
  docs/video/video_zone_v2.md
  docs/vip/action.md
  docs/vip/info.md
Labels: 主站杂项/Misc
